import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <Button
          variant="ghost"
          onClick={() => navigate("/")}
          className="mb-8"
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Home
        </Button>

        <h1 className="text-4xl font-bold mb-8 bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
          Terms of Service
        </h1>

        <div className="space-y-6 text-muted-foreground">
          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using n3os AI Agent Systems, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">2. Use of Services</h2>
            <p>
              Our AI-powered tools and agents are provided "as is" for creative and productivity purposes. You agree to use these services responsibly and in accordance with applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">3. AI-Generated Content</h2>
            <p>
              Content generated by our AI agents may contain errors or inaccuracies. You are responsible for verifying all AI-generated outputs before use in production or commercial projects. n3os is not liable for any damages resulting from the use of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">4. Intellectual Property</h2>
            <p>
              You retain all rights to content you upload. By using our AI tools, you grant n3os a limited licence to process your content for the purpose of providing our services. AI-generated outputs may be used by you under our standard licence terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">5. Account Responsibilities</h2>
            <p>
              You are responsible for maintaining the security of your account credentials. Any activity performed under your account is your responsibility. Notify us immediately of any unauthorised access.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">6. Limitations of Liability</h2>
            <p>
              n3os shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of our services, including but not limited to loss of data, revenue, or business opportunities.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">7. Service Modifications</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue any aspect of our services at any time without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">8. Termination</h2>
            <p>
              We may terminate or suspend your access to our services at any time, with or without cause or notice, for conduct that we believe violates these Terms of Service or is harmful to other users, us, or third parties.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">9. Changes to Terms</h2>
            <p>
              We reserve the right to update these Terms of Service at any time. Continued use of our services after changes constitutes acceptance of the modified terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">10. Contact</h2>
            <p>
              For questions about these Terms of Service, contact us at <a href="mailto:n3o@n3os.com" className="text-primary hover:text-secondary transition-colors">n3o@n3os.com</a>.
            </p>
          </section>

          <div className="mt-12 pt-8 border-t border-border/50">
            <p className="text-sm">
              Last updated: March 6, 2026
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;
